Repository Developer-DAO/web3-ui, pull requests merged in 2021-12, with the labels that each got.

#88 set Storybook default viewmode to "Docs"
  .storybook/preview.js
Labels: enhancement

#121 Token gate
  .changeset/two-turtles-march.md
  packages/components/src/components/TokenGate/TokenGate.stories.tsx
  packages/components/src/components/TokenGate/TokenGate.tsx
  packages/components/src/components/TokenGate/index.ts
Labels: component

#164 added null check for value prop
  .changeset/yellow-eyes-eat.md
  packages/components/src/components/Address/Address.tsx
Labels: bug
